spring.application.name=booking-backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.flyway.enabled=true
spring.profiles.active=dev

logging.level.root=INFO
logging.level.finki.ukim.emt.booking=DEBUG
logging.level.org.springframework=WARN

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer


