spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
jwt.secret=DyZYAK22iz72AceuM6KcREs4pw9C7VZ2NzULDAUsfBAo7xgIKB3HKnxWM1AHOC9SN1PjLWjc41iqnrfrsmDHtQ==

